### ISSUE TITLE
In user interface if register an account (in the up message) is pressed then is loaded a blank page

### ISSUE THREAD

**Issue by PeopleInside** [osTicket/osTicket-1.8#2024] opened 2015-05-07 16:41 UTC
![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/7520619/3e3037c8-f4e8-11e4-8d65-4ef448ff8d17.png)

If user press register

![immagine senza nome](https://cloud.githubusercontent.com/assets/5006150/7520669/a0b3dae4-f4e8-11e4-9bcd-20942f82b932.png)

**Comment by ntozier** [comment] 2015-05-07 16:46
That link works in my installation.
![capture](https://cloud.githubusercontent.com/assets/1315768/7520766/21d7c6c6-f4b7-11e4-974a-c50c4240fe3b.PNG)

**Comment by PeopleInside** [comment] 2015-05-07 16:49
I tried with a fresh install on my server and didn't work so if something
not supported by the server should be a check during install process..

I don't know why is not working on my server but tested with fresh install
of OsTicket, English bit also with Italian language file.

Is required something of particular for make it work?

Inviato da dispositivo mobile. | Sended  by mobile device
Il 07/Mag/2015 18:46, "ntozier" <notifications@github.com> ha scritto:

**Comment by PeopleInside** [comment] 2015-05-07 16:54
Interesting, from my phone if I put the direct link in browser work.

Did you tried from user interface on open ticket where user is guest or you tried to put direct URL into browser?

**Comment by ntozier** [comment] 2015-05-07 17:07
I tried direct url, and I used the link on my open page since I don't have that link on my landing page.
http://support.harborhomes.org/open.php

**Comment by PeopleInside** [comment] 2015-05-07 17:12
Ok so sorry but your test is not valid for diagnosis. Direct link works
also for me.

How to reproduce:
1. Create a ticket from not logged and not registered client side
2. If you follow the link on the email you will se the ticket and in top
you have create an account link. If you click that as showed in the image
is loaded a blank page.

Tested now from my smartphone and I can reproduce also from there

Inviato da dispositivo mobile. | Sended  by mobile device
Il 07/Mag/2015 19:07, "ntozier" <notifications@github.com> ha scritto:

**Comment by ntozier** [comment] 2015-05-07 17:15
"Create a ticket from not logged and not registered client side"

I cannot possibly do that.  My installations ALL require the person to be logged in to create a ticket.  Clicking on Open a ticket takes me to a login screen with the link to register (create an account) on it.

What version are you running?

**Comment by PeopleInside** [comment] 2015-05-07 17:18
Last version.
Your is only a settings.

I can also force user to register to see ticket but I want alow also not
registered user.

So registration is not mandatory in my OsTicket and I found this issue.

Inviato da dispositivo mobile. | Sended  by mobile device
Il 07/Mag/2015 19:16, "ntozier" <notifications@github.com> ha scritto:

**Comment by PeopleInside** [comment] 2015-05-07 17:18
https://www.peopleinside.it/liveticket/

Inviato da dispositivo mobile. | Sended  by mobile device
Il 07/Mag/2015 19:18, "Marco Borla" <ocispposta@gmail.com> ha scritto:

**Comment by ntozier** [comment] 2015-05-07 17:25
I tried your system and get the result that your seeing.
Are you seeing any errors in your PHP error log?
Apache error log?

**Comment by PeopleInside** [comment] 2015-05-07 17:33
yes
[Thu May 07 18:07:50 2015] [error] [client] PHP Fatal error:  Call to a member function getField() on a non-object in liveticket/account.php on line 35, referer: liveticket/tickets.php?id=11

[Thu May 07 19:24:51 2015] [error] PHP Fatal error:  Call to a member function getField() on a non-object in /account.php on line 35, referer: liveticket/tickets.php?id=13

**Comment by PeopleInside** [comment] 2015-05-08 08:27
PHP Fatal error:  Call to a member function getField() on a non-object in /liveticket/account.php on line 35, referer: /liveticket/tickets.php?id=12

**Comment by PeopleInside** [comment] 2015-05-08 10:04
I had no checked if Login link in the pop up do the same. I want know if this is a bug i think it can be.

**Comment by greezybacon** [comment] 2015-05-08 12:09
I've seen this error in PHP error logs before but haven't been able to track down a cause. @PeopleInside  thanks for the detailed information

**Comment by markus4000** [comment] 2015-05-15 15:35
I can confirm. I have the same in 1.9.7

**Comment by PeopleInside** [comment] 2015-05-22 13:37
will be this fixed?

**Comment by greezybacon** [comment] 2015-05-22 18:59
@PeopleInside we have over 700 open issues and over 70 confirmed bugs. And, we're working on stabilizing a new release with lots of cool features. I apologize for the delays. Any help is welcomed.

**Comment by PeopleInside** [comment] 2015-06-08 15:56
I understood the cause.
The blank page there are only if you are logged as Guest.

Like customer clicks on the link of the ticket email so are logged into ticket as Guest.
In this case registration link doesn't work, login link works and redirect the user to the log in page but also in this log in page if you press the register link you can't register. So if you go back to login page you will see on top right you are logged as guest so logout and now you are able to register an account.

This is the issue, the link in the email make user to be logged as guest and something not works when user want register from this page where are logged as guest.

**Comment by PeopleInside** [comment] 2015-06-08 17:31
suggested solution: Register link in top will open in a new window and when user click on it is been logged out from Guest user.

This may cause issue on the window where ticket is opened because what happened if user refresh the page or write something after clicking on register link on top?

So i don't know if you can fix in different way for avoid this issue.
Now we know the blank page seems to be showed because user are logged in as Guest.

**Comment by matlinuxer2** [comment] 2015-09-18 09:47
I got the same problem and got error log like this:

====
 Fatal error: Call to a member function getField() on null in ******/osTicket-1.8/account.php on line 35
====

**Comment by matlinuxer2** [comment] 2015-09-19 04:28
```
 31     if ($thisclient->isGuest()) {                                                                 
 32         foreach ($thisclient->getForms() as $f)
 33             if ($f->get('type') == 'U')
 34                 $user_form = $f;
 35         $user_form->getField('email')->configure('disabled', true);
 36     }
```
I did some debug work, and I found something below:
1. at line of 32, "$thisclient->getForms()" got an array containing one item.
2. at line of 33, "$f->get('type') always return "bool(false)"
3. at line of 35, the "$user_form" is always "NULL" , and cause error.

I hope to try to fix it, but I do not understand the data structure of "Forms" ( which the"$thisclient->getForms()" returns ).

Any suggestion?

**Comment by adriencarbonne** [comment] 2015-10-20 15:50
I can confirm that this commit solves the bug.

**Comment by greezybacon** [comment] 2015-10-20 18:34
Since it's already merged, I'll close the issue. Please comment or reopen if the issue persists.

**Closed by greezybacon** 2015-10-20 18:34 UTC
Labels: bug

**Comment by robec1982** [comment] 2015-11-03 17:27
Thanks to @matlinuxer2 for solving this bug. I also followed his changes and my osTicket registration is working like a charm...

**Comment by Luis-PvxPlus** [comment] 2016-01-13 18:52
This looks similar to the problem that I reported on issue 2861.
Could this solution also solve the "Server Error 500" that I'm getting with those same links?
Click here: https://github.com/osTicket/osTicket-1.8/issues/2861

or visit my osticket forum thread here:
http://www.osticket.com/forum/discussion/87118/broken-registration-links-when-signed-in-with-a-ticket

**Comment by Luis-PvxPlus** [comment] 2016-01-13 19:17
Good news!  This fix solved my problem too.  Thank you @matlinuxer2 !

**Comment by aldren07** [comment] 2017-02-24 11:07
Hi,

I'm a newbie here, so please bear with me.

I successfully installed osticket v1.10 but when I tried to login as an end user and "Create an account", the Information doesn't show-up. I can only see Preferences and Access Credentials.

Can you please help me. Thanks

**Comment by aldren07** [comment] 2017-02-24 11:08
Hi,

Please see screenshot. Thanks.
![screenshot_1](https://cloud.githubusercontent.com/assets/26002882/23301378/9b26f456-fac4-11e6-8ad7-1c179ee9ebad.jpg)
