### ISSUE TITLE
Advance search bug

### ISSUE THREAD

**Issue by henrycoule** [osTicket/osTicket-1.8#993] opened 2014-06-05 19:06 UTC
Since v1.8.x the advanced search had never displayed the right results. Now I am on v1.9.1 and when I click on the advanced search and choose "unassigned" it literally gives me the result for all the tickets in the system. 

Now out of curiosity if I choose a date range it will give me a smaller resultset (of tickets not assigned) but when I click to view the results they are all tickets which are already assigned to someone. It is literally not doing what the options says and this is happening for any option you choose.

Additionally, on the dashboard, the graph does not show up. it is just blank

![unassigned](https://cloud.githubusercontent.com/assets/6393255/3192206/6503208a-ece3-11e3-95d0-2ce4561631c7.png)

**Comment by greezybacon** [comment] 2015-03-17 20:31
@henrycoule can you verify if the patch in #1857 addresses the search for unassigned tickets?

**Comment by henrycoule** [comment] 2015-03-19 12:54
@greezybacon  I tested this patch and it seems to work to a degree howerver; I am not getting the logic. When I choose "Any Status", "All departments", "Any flags", "Unassigned", "All help topics", "Closed by: Anyone"  I get only one result. I had a ticked which is unassigned and I chose the status "In Progress" however it appears the advanced search using the options listed above only searches 'open tickets' queue. Why not tickets with 'closed status' since I chose "Any Status" ?
![adv_scr_shot](https://cloud.githubusercontent.com/assets/6393255/6730726/37b0ffe2-ce0d-11e4-95e6-d09cef3c7aac.png)

**Comment by greezybacon** [comment] 2015-03-19 14:01
Tickets are considered assigned when they are closed. That's how the system tracks the closed-by agent

**Comment by henrycoule** [comment] 2015-03-19 14:21
@greezybacon  Hmmm... I took a closer look and it appears whoever closes the ticket gets assigned to the ticket when it isn't originally assigned. Is this happening only when it is unassigned?  I created a new user to test out this logic and indeed this is what is happening. If "Agent A" is the owner or the one the ticket is assigned to if "Agent B" closes the ticket, the ticket now gets assigned to "Agent B" I don't think this should happen.

There are times the agents assigned to the ticket may not be around and the ticket may be considered resolved (at least for now) if I close the ticket, it shouldn't get assigned to me. What if the issue reoccurs? And the users reopens the ticket? Now it comes to me. We should have a different way of tracking closed by and assigned and the two shouldn't be considered as the same thing.

**Comment by greezybacon** [comment] 2015-03-19 14:23
@henrycoule the ticket is unassigned on reopen. It is then assigned to the last respondent. That might be you and it might be agent A. If no one has responded, then then the ticket will be unassigned when it is reopened, similar to a new ticket.

**Comment by henrycoule** [comment] 2015-03-19 14:28
@greezybacon That's now how it is working. I tested it. The ticket was new, unassigned and not responded to by any Agent. I closed it then it was marked as "closed by ME" then I reopened it and it was assigned to me. Agent B closed the ticket and it was marked as "Closed by Agent B" Agent B reopens it and now it is assigned to Agent B
![ua](https://cloud.githubusercontent.com/assets/6393255/6732502/4560ffa4-ce1a-11e4-8e65-fc1ac9df2e5b.png)

**Comment by greezybacon** [comment] 2015-03-19 14:40
@henrycoule pardon me. The way the logic is currently written, the assignee is not cleared on a forced reopen (reopen by agent). Therefore the original assignee is lost and the person who closes it will remain assigned. Maybe you shouldn't be closing other people's tickets.

**Comment by henrycoule** [comment] 2015-03-19 15:37
@greezybacon It still does not even work the way you are describing it. I let "Agent B" respond to the ticket then "Agent A" closed the ticket, then the user/customer responded to the ticket which caused it to reopened. When it did reopened it was assigned to "Agent A" and not "Agent B"

Also consider a supervisor or a manager can close a ticket which is assigned to an agent and the same behaviour I am describing is the effect I see here. A supervisor or manager should be able to close a ticket and the logic shouldn't assign the ticket to him. More importantly, on reopen by a user (not an agent) it shouldn't be assigned to the last person who closed the ticket. I can reproduce this any time.

osTicket (v1.9.6-12-g62d99b1)

**Comment by protich** [comment] 2015-03-19 15:55
@henrycoule -- the logic as you described is by design. Closing agent gets assigned the ticket on reopen... if you close a ticket then it's your responsibility to handle it if it gets reopened. I understand that's not how _your_ workflow functions,  but for a large percentage of use cases __it is__ the expected behavior.

**Comment by henrycoule** [comment] 2015-03-19 19:55
@protich I believe it is far more efficient not to assign a ticket to a closing agent. It makes sense to note who closed it but to assign the ticket to the closing agents defeats the purpose of having a manager or assigning a manager role in the ticket system; who can close tickets because based on the interactions feels it has been well answered. The manager may not necessarily wants to own or assign the ticket to himself. I believe we have a way of assigning tickets to agents if we wants to. We also have a way of claiming unassigned tickets if we wants to, so the mere fact a ticket is closed shouldn't be assigned to me.  Imaging, an agent with a manager role in the ticket system reviews and closes 50 tickets, which after a while gets opened by the user, he now as to reassign to the agent again whereas if it was not assigned to the closing agent, the agent who claimed the ticket takes responsibility.

**Comment by henrycoule** [comment] 2015-03-20 12:38
@greezybacon @protich I have an idea... so how about having an option which you can choose whether to assign ticket to "closing agent" or not ?

**Closed** 2015-03-23 20:02 UTC
Labels: bug, duplicate
