### ISSUE TITLE
Missing attachment on new ticket create

### ISSUE THREAD

**Issue by PlamenVasilev** [osTicket/osTicket-1.8#2099] opened 2015-05-21 12:15 UTC
When I create new ticket, click on "send alert to user" and than write the ticket and attach file the attachment is uploaded into the ticket, but it is not sent to the user with the alert.
the email is without attachment, but in the ticket the file is uploaded successfully

**Comment by ntozier** [comment] 2015-05-21 13:51
1. Send alert to user. is checked by default, so it sounds to me like you are unchecking it.  Which would of course result in the alert not being sent to the user.

2. Last I checked the system does not email attachments.  This is by design.

**Comment by PlamenVasilev** [comment] 2015-05-21 13:56
NO.
It is checked and i want to send alert for the new ticket and attach file.
the alert is sent, but no attachment!

**Comment by protich** [comment] 2015-05-21 14:16
@PlamenVasilev - This is by design. Alerts and notices don't include attachments! It's meant to simply _alert_ agents so they can login to the system to view the entirety of the thread. 

That said, in the future version we're planning on adding ability to send out attachments as well.

**Comment by PlamenVasilev** [comment] 2015-05-21 14:25
In our case we want to open ticket to someone and tell him that something is wrong and he have to do something and we want to attach additional info showing him the problem.
Now we have to open empty ticket, be careful to uncheck "send alert" and than to write second comment inside the empty ticket and than to attach the file.

I understand that alerts and notices should not contain attachments, but on new ticket the attachments should be send.

**Comment by ntozier** [comment] 2015-05-21 15:16
This appears to be a duplicate feature request, not a bug/issue report.
Please close this and see: https://github.com/osTicket/osTicket-1.8/issues/1170

**Closed** 2015-05-21 15:17 UTC
